// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC7zG3VO2ccuBZCRyPN1U8iZlgNIiHnXI',
    appId: '1:189883996833:web:17730f944293d92dc26ee0',
    messagingSenderId: '189883996833',
    projectId: 'stasiunmini',
    authDomain: 'stasiunmini.firebaseapp.com',
    databaseURL: 'https://stasiunmini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stasiunmini.firebasestorage.app',
    measurementId: 'G-6KP7Z7QEDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEloF_VgK94Qs2t76Wj3uNiI6L0zibQck',
    appId: '1:189883996833:android:95094613afbdbb31c26ee0',
    messagingSenderId: '189883996833',
    projectId: 'stasiunmini',
    databaseURL: 'https://stasiunmini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stasiunmini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkffL5SMvBk_r3Dka6D9Hy004OpNy32pg',
    appId: '1:189883996833:ios:f26a20a47b7419adc26ee0',
    messagingSenderId: '189883996833',
    projectId: 'stasiunmini',
    databaseURL: 'https://stasiunmini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stasiunmini.firebasestorage.app',
    iosBundleId: 'com.example.gladiBanget',
  );

}